// <auto-generated />
using System;
using CapitecFraud.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapitecFraud.Infrastructure.Migrations
{
    [DbContext(typeof(CapitecFraudDbContext))]
    [Migration("20260524144900_UpdateDevicesTable")]
    partial class UpdateDevicesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapitecFraud.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiskScore")
                        .HasColumnType("int");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CapitecFraud.Domain.Entities.FraudDecisionRuleConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BlockThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewThreshold")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FraudDecisionRuleConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BlockThreshold = 85,
                            Name = "Large Amount Anomaly",
                            ReviewThreshold = 60
                        },
                        new
                        {
                            Id = 2L,
                            BlockThreshold = 80,
                            Name = "High Velocity Transactions",
                            ReviewThreshold = 55
                        },
                        new
                        {
                            Id = 3L,
                            BlockThreshold = 90,
                            Name = "Structuring (Just Below Threshold Pattern)",
                            ReviewThreshold = 65
                        },
                        new
                        {
                            Id = 4L,
                            BlockThreshold = 75,
                            Name = "Impossible Travel (Geo Velocity)",
                            ReviewThreshold = 50
                        },
                        new
                        {
                            Id = 5L,
                            BlockThreshold = 85,
                            Name = "New Device + High Value Transaction",
                            ReviewThreshold = 60
                        },
                        new
                        {
                            Id = 6L,
                            BlockThreshold = 70,
                            Name = "VPN / Proxy Detected",
                            ReviewThreshold = 45
                        },
                        new
                        {
                            Id = 7L,
                            BlockThreshold = 80,
                            Name = "Unusual Country Risk",
                            ReviewThreshold = 55
                        },
                        new
                        {
                            Id = 8L,
                            BlockThreshold = 90,
                            Name = "Password Reset Followed by Transaction",
                            ReviewThreshold = 65
                        },
                        new
                        {
                            Id = 9L,
                            BlockThreshold = 75,
                            Name = "Multiple Failed Login Attempts",
                            ReviewThreshold = 50
                        },
                        new
                        {
                            Id = 10L,
                            BlockThreshold = 95,
                            Name = "SIM Swap Indicator Detected",
                            ReviewThreshold = 70
                        },
                        new
                        {
                            Id = 11L,
                            BlockThreshold = 85,
                            Name = "First-Time Beneficiary Large Transfer",
                            ReviewThreshold = 60
                        },
                        new
                        {
                            Id = 12L,
                            BlockThreshold = 80,
                            Name = "High-Risk Merchant Category",
                            ReviewThreshold = 55
                        },
                        new
                        {
                            Id = 13L,
                            BlockThreshold = 78,
                            Name = "Card-Not-Present High Value Transaction",
                            ReviewThreshold = 50
                        },
                        new
                        {
                            Id = 14L,
                            BlockThreshold = 88,
                            Name = "Shared Device Across Multiple Accounts",
                            ReviewThreshold = 65
                        },
                        new
                        {
                            Id = 15L,
                            BlockThreshold = 95,
                            Name = "Circular Money Flow Detected",
                            ReviewThreshold = 70
                        },
                        new
                        {
                            Id = 16L,
                            BlockThreshold = 80,
                            Name = "Multiple Accounts Same IP Address",
                            ReviewThreshold = 55
                        },
                        new
                        {
                            Id = 17L,
                            BlockThreshold = 75,
                            Name = "Sudden Spending Behavior Change",
                            ReviewThreshold = 50
                        },
                        new
                        {
                            Id = 18L,
                            BlockThreshold = 85,
                            Name = "Dormant Account Sudden Activity",
                            ReviewThreshold = 60
                        },
                        new
                        {
                            Id = 19L,
                            BlockThreshold = 70,
                            Name = "Abnormal Transaction Time Pattern",
                            ReviewThreshold = 45
                        },
                        new
                        {
                            Id = 20L,
                            BlockThreshold = 65,
                            Name = "High Risk Combination (New Device + New Payee + High Amount)",
                            ReviewThreshold = 40
                        },
                        new
                        {
                            Id = 21L,
                            BlockThreshold = 95,
                            Name = "Account Takeover Pattern Detected",
                            ReviewThreshold = 70
                        });
                });

            modelBuilder.Entity("CapitecFraud.Domain.Entities.FraudFlag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FraudResultId")
                        .HasColumnType("bigint");

                    b.Property<string>("Operator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScoreImpact")
                        .HasColumnType("int");

                    b.Property<string>("TriggerValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FraudResultId");

                    b.ToTable("FraudFlags");
                });

            modelBuilder.Entity("CapitecFraud.Domain.Entities.FraudResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ResultDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RiskScore")
                        .HasColumnType("int");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("FraudResults");
                });

            modelBuilder.Entity("CapitecFraud.Domain.Entities.RuleConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ActionWeight")
                        .HasColumnType("int");

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RuleConfig");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ActionWeight = 30,
                            Field = "Amount",
                            IsActive = true,
                            Name = "Large Transaction Amount",
                            Operator = ">",
                            Value = "20000"
                        },
                        new
                        {
                            Id = 2L,
                            ActionWeight = 50,
                            Field = "Amount",
                            IsActive = true,
                            Name = "Very Large Transaction Amount",
                            Operator = ">",
                            Value = "50000"
                        },
                        new
                        {
                            Id = 3L,
                            ActionWeight = 35,
                            Field = "TransactionCountLast10Min",
                            IsActive = true,
                            Name = "High Velocity Transactions",
                            Operator = ">",
                            Value = "5"
                        },
                        new
                        {
                            Id = 4L,
                            ActionWeight = 45,
                            Field = "TransactionCountLast1Min",
                            IsActive = true,
                            Name = "Excessive Velocity Transactions",
                            Operator = ">",
                            Value = "3"
                        },
                        new
                        {
                            Id = 5L,
                            ActionWeight = 40,
                            Field = "CountryChangeLast24H",
                            IsActive = true,
                            Name = "Country Change Anomaly",
                            Operator = ">",
                            Value = "1"
                        },
                        new
                        {
                            Id = 6L,
                            ActionWeight = 60,
                            Field = "GeoDistanceKmPerHour",
                            IsActive = true,
                            Name = "Impossible Travel Detected",
                            Operator = ">",
                            Value = "900"
                        },
                        new
                        {
                            Id = 7L,
                            ActionWeight = 35,
                            Field = "CountryRiskScore",
                            IsActive = true,
                            Name = "High Risk Country",
                            Operator = ">",
                            Value = "70"
                        },
                        new
                        {
                            Id = 8L,
                            ActionWeight = 25,
                            Field = "IsNewDevice",
                            IsActive = true,
                            Name = "New Device Usage",
                            Operator = "=",
                            Value = "true"
                        },
                        new
                        {
                            Id = 9L,
                            ActionWeight = 50,
                            Field = "DeviceAccountCount",
                            IsActive = true,
                            Name = "Device Shared Across Multiple Accounts",
                            Operator = ">",
                            Value = "3"
                        },
                        new
                        {
                            Id = 10L,
                            ActionWeight = 55,
                            Field = "DeviceRiskScore",
                            IsActive = true,
                            Name = "Suspicious Device Fingerprint",
                            Operator = ">",
                            Value = "80"
                        },
                        new
                        {
                            Id = 11L,
                            ActionWeight = 50,
                            Field = "PasswordResetLastMinutes",
                            IsActive = true,
                            Name = "Password Reset Before Transaction",
                            Operator = "<",
                            Value = "30"
                        },
                        new
                        {
                            Id = 12L,
                            ActionWeight = 35,
                            Field = "FailedLoginAttempts",
                            IsActive = true,
                            Name = "Multiple Failed Login Attempts",
                            Operator = ">",
                            Value = "3"
                        },
                        new
                        {
                            Id = 13L,
                            ActionWeight = 30,
                            Field = "OtpResendCount",
                            IsActive = true,
                            Name = "OTP Resend Abuse",
                            Operator = ">",
                            Value = "5"
                        },
                        new
                        {
                            Id = 14L,
                            ActionWeight = 25,
                            Field = "IsNewBeneficiary",
                            IsActive = true,
                            Name = "First Time Beneficiary",
                            Operator = "=",
                            Value = "true"
                        },
                        new
                        {
                            Id = 15L,
                            ActionWeight = 45,
                            Field = "MerchantCategory",
                            IsActive = true,
                            Name = "High Risk Merchant Category",
                            Operator = "IN",
                            Value = "CRYPTO,GAMBLING,FOREX,GIFT_CARDS"
                        },
                        new
                        {
                            Id = 16L,
                            ActionWeight = 20,
                            Field = "TransactionChannel",
                            IsActive = true,
                            Name = "Card Not Present High Value",
                            Operator = "=",
                            Value = "CNP"
                        },
                        new
                        {
                            Id = 17L,
                            ActionWeight = 40,
                            Field = "IpAccountCount",
                            IsActive = true,
                            Name = "Shared IP Across Accounts",
                            Operator = ">",
                            Value = "5"
                        },
                        new
                        {
                            Id = 18L,
                            ActionWeight = 45,
                            Field = "DeviceAccountCount",
                            IsActive = true,
                            Name = "Shared Device Across Accounts",
                            Operator = ">",
                            Value = "3"
                        },
                        new
                        {
                            Id = 19L,
                            ActionWeight = 70,
                            Field = "CircularFlowDetected",
                            IsActive = true,
                            Name = "Circular Money Flow Detected",
                            Operator = "=",
                            Value = "true"
                        },
                        new
                        {
                            Id = 20L,
                            ActionWeight = 30,
                            Field = "DaysSinceLastTransaction",
                            IsActive = true,
                            Name = "Dormant Account Reactivation",
                            Operator = ">",
                            Value = "90"
                        },
                        new
                        {
                            Id = 21L,
                            ActionWeight = 35,
                            Field = "SpendingDeviationPercent",
                            IsActive = true,
                            Name = "Sudden Spending Spike",
                            Operator = ">",
                            Value = "300"
                        },
                        new
                        {
                            Id = 22L,
                            ActionWeight = 15,
                            Field = "IsUnusualHour",
                            IsActive = true,
                            Name = "Unusual Transaction Time",
                            Operator = "=",
                            Value = "true"
                        },
                        new
                        {
                            Id = 23L,
                            ActionWeight = 75,
                            Field = "CompositeRisk",
                            IsActive = true,
                            Name = "New Device + New Beneficiary + High Amount",
                            Operator = "=",
                            Value = "TRUE"
                        },
                        new
                        {
                            Id = 24L,
                            ActionWeight = 80,
                            Field = "RiskSignalCount",
                            IsActive = true,
                            Name = "Multiple High Risk Signals Detected",
                            Operator = ">",
                            Value = "3"
                        });
                });

            modelBuilder.Entity("CapitecFraud.Domain.Models.AccountDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("AccountDevices");
                });

            modelBuilder.Entity("CapitecFraud.Domain.Models.Device", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Fingerprint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("CapitecFraud.Domain.Models.TransactionMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerchantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CapitecFraud.Domain.Entities.FraudFlag", b =>
                {
                    b.HasOne("CapitecFraud.Domain.Entities.FraudResult", null)
                        .WithMany("Flags")
                        .HasForeignKey("FraudResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CapitecFraud.Domain.Models.AccountDevice", b =>
                {
                    b.HasOne("CapitecFraud.Domain.Models.Device", "Device")
                        .WithMany("AccountDevices")
                        .HasForeignKey("DeviceId");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CapitecFraud.Domain.Entities.FraudResult", b =>
                {
                    b.Navigation("Flags");
                });

            modelBuilder.Entity("CapitecFraud.Domain.Models.Device", b =>
                {
                    b.Navigation("AccountDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
