// <auto-generated />
using System;
using CapitecFraud.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapitecFraud.Infrastructure.Migrations
{
    [DbContext(typeof(CapitecFraudDbContext))]
    [Migration("20260522194014_AddRulesConfigrationData")]
    partial class AddRulesConfigrationData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapitecFraud.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiskScore")
                        .HasColumnType("int");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CapitecFraud.Domain.Entities.FraudDecisionRuleConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BlockThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewThreshold")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FraudDecisionRuleConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BlockThreshold = 85,
                            Name = "Large Amount Anomaly",
                            ReviewThreshold = 60
                        },
                        new
                        {
                            Id = 2L,
                            BlockThreshold = 80,
                            Name = "High Velocity Transactions",
                            ReviewThreshold = 55
                        },
                        new
                        {
                            Id = 3L,
                            BlockThreshold = 90,
                            Name = "Structuring (Just Below Threshold Pattern)",
                            ReviewThreshold = 65
                        },
                        new
                        {
                            Id = 4L,
                            BlockThreshold = 75,
                            Name = "Impossible Travel (Geo Velocity)",
                            ReviewThreshold = 50
                        },
                        new
                        {
                            Id = 5L,
                            BlockThreshold = 85,
                            Name = "New Device + High Value Transaction",
                            ReviewThreshold = 60
                        },
                        new
                        {
                            Id = 6L,
                            BlockThreshold = 70,
                            Name = "VPN / Proxy Detected",
                            ReviewThreshold = 45
                        },
                        new
                        {
                            Id = 7L,
                            BlockThreshold = 80,
                            Name = "Unusual Country Risk",
                            ReviewThreshold = 55
                        },
                        new
                        {
                            Id = 8L,
                            BlockThreshold = 90,
                            Name = "Password Reset Followed by Transaction",
                            ReviewThreshold = 65
                        },
                        new
                        {
                            Id = 9L,
                            BlockThreshold = 75,
                            Name = "Multiple Failed Login Attempts",
                            ReviewThreshold = 50
                        },
                        new
                        {
                            Id = 10L,
                            BlockThreshold = 95,
                            Name = "SIM Swap Indicator Detected",
                            ReviewThreshold = 70
                        },
                        new
                        {
                            Id = 11L,
                            BlockThreshold = 85,
                            Name = "First-Time Beneficiary Large Transfer",
                            ReviewThreshold = 60
                        },
                        new
                        {
                            Id = 12L,
                            BlockThreshold = 80,
                            Name = "High-Risk Merchant Category",
                            ReviewThreshold = 55
                        },
                        new
                        {
                            Id = 13L,
                            BlockThreshold = 78,
                            Name = "Card-Not-Present High Value Transaction",
                            ReviewThreshold = 50
                        },
                        new
                        {
                            Id = 14L,
                            BlockThreshold = 88,
                            Name = "Shared Device Across Multiple Accounts",
                            ReviewThreshold = 65
                        },
                        new
                        {
                            Id = 15L,
                            BlockThreshold = 95,
                            Name = "Circular Money Flow Detected",
                            ReviewThreshold = 70
                        },
                        new
                        {
                            Id = 16L,
                            BlockThreshold = 80,
                            Name = "Multiple Accounts Same IP Address",
                            ReviewThreshold = 55
                        },
                        new
                        {
                            Id = 17L,
                            BlockThreshold = 75,
                            Name = "Sudden Spending Behavior Change",
                            ReviewThreshold = 50
                        },
                        new
                        {
                            Id = 18L,
                            BlockThreshold = 85,
                            Name = "Dormant Account Sudden Activity",
                            ReviewThreshold = 60
                        },
                        new
                        {
                            Id = 19L,
                            BlockThreshold = 70,
                            Name = "Abnormal Transaction Time Pattern",
                            ReviewThreshold = 45
                        },
                        new
                        {
                            Id = 20L,
                            BlockThreshold = 65,
                            Name = "High Risk Combination (New Device + New Payee + High Amount)",
                            ReviewThreshold = 40
                        },
                        new
                        {
                            Id = 21L,
                            BlockThreshold = 95,
                            Name = "Account Takeover Pattern Detected",
                            ReviewThreshold = 70
                        });
                });

            modelBuilder.Entity("CapitecFraud.Domain.Entities.FraudFlag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FraudResultId")
                        .HasColumnType("bigint");

                    b.Property<string>("Operator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScoreImpact")
                        .HasColumnType("int");

                    b.Property<string>("TriggerValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FraudResultId");

                    b.ToTable("FraudFlags");
                });

            modelBuilder.Entity("CapitecFraud.Domain.Entities.FraudResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiskScore")
                        .HasColumnType("int");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("FraudResults");
                });

            modelBuilder.Entity("CapitecFraud.Domain.Entities.RuleConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ActionWeight")
                        .HasColumnType("int");

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RuleConfig");
                });

            modelBuilder.Entity("CapitecFraud.Domain.Entities.FraudFlag", b =>
                {
                    b.HasOne("CapitecFraud.Domain.Entities.FraudResult", null)
                        .WithMany("Flags")
                        .HasForeignKey("FraudResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CapitecFraud.Domain.Entities.FraudResult", b =>
                {
                    b.Navigation("Flags");
                });
#pragma warning restore 612, 618
        }
    }
}
