services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    # container_name: capitec-fraud-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Strong@Passw0rd123"
    ports:
      - "1433:1433"
    networks:
      - capitec-fraud-net

  redis:
    image: redis:7
    container_name: capitec-fraud-redis
    ports:
      - "6379:6379"
    networks:
      - capitec-fraud-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: capitec-fraud-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - capitec-fraud-net

  api:
    build:
      context: .
      dockerfile: src/CapitecFraudEngine/CapitecFraud.Api/Dockerfile
    container_name: capitec-fraud-api
    depends_on:
      - redis
      - rabbitmq
      - sqlserver
    ports:
      - "5001:8080"
      - "5005:5005"
    environment:
      ConnectionStrings__CapitecFraudDb: "Server=sqlserver,1433;Database=CapitecFraudDb;User Id=sa;Password=Strong@Passw0rd123;Encrypt=False;TrustServerCertificate=True"
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_USE_POLLING_FILE_WATCHER: "true" 
      DOTNET_WATCH: "1"
    networks:
      - capitec-fraud-net

  worker:
    build:
      context: .
      dockerfile: src/CapitecFraudEngine/CapitecFraud.Worker/Dockerfile
    container_name: capitec-fraud-worker
    depends_on:
      - sqlserver
      - redis
      - rabbitmq
    environment:
      ConnectionStrings__CapitecFraudDb: "Server=sqlserver,1433;Database=CapitecFraudDb;User Id=sa;Password=Strong@Passw0rd123;Encrypt=False;TrustServerCertificate=True"
    networks:
      - capitec-fraud-net

networks:
  capitec-fraud-net:
    name: capitec-fraud-net
    driver: bridge